# Use the latest Node.js version as the base image
FROM node:latest AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY Dh-booking/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY Dh-booking/. .

# Build the application
RUN npm run build

# Create a new image with a smaller base image
FROM nginx:alpine

# Copy nginx configuration file
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy the build files from the builder stage to the new image
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start the nginx server
CMD ["nginx", "-g", "daemon off;"]