image: hashicorp/terraform:latest

variables:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

stages:
  - terraform-plan

terraform-plan:
  stage: terraform-plan
  script:
    - cd terraform
    - terraform init
    - terraform plan -out=plan.out
  artifacts:
    paths:
      - terraform/plan.out

terraform-apply:
  stage: terraform-apply
  when: manual
  script:
    - cd terraform
    - terraform apply "plan.out"
